export const productList: string[] = ["blue pant"
    , "black pant"
    , "blue shirt"
    , "black shoes"
    , "brown shoes"
    , "white pant"
    , "white shoes"
    , "red shirt"
    , "gray pant"
    , "white shirt"
    , "golden shoes"
    , "dark pant"
    , "pink shirt"
    , "yellow pant"];